module.exports = {
  siteTitle: 'EEジョブズ',
  siteTitleAlt: 'WEBエンジニア向け英語求人まとめ',
  publisher: 'ヤバイWEB屋さん',
  siteDescription:
    'エンジニア向け英語が使える求人まとめサイト。仕事で英語が使えるWEB系エンジニア向けの求人をまとめています。',
  siteUrl: 'https://en-jobs.yabaiwebyasan.com',
  postsPerHomePage: 16,
  postsPerPage: 15,
  author: 'ヤバイWEB屋さん',
  authorUrl: 'https://en-jobs.yabaiwebyasan.com/about',
  userTwitter: '@yabaiwebyasan',
  shortTitle: 'EE Jobs',
  shareImage: '/logos/siteShare.png',
  shareImageWidth: 1200,
  shareImageHeight: 630,
  siteLogo: '/logos/logo-512.png',
  backgroundColor: '#e9e9e9',
  themeColor: '#121212',
  copyright: 'Copyright © 2019 EE Jobs',
}
